# Generated by Django 2.2.2 on 2019-06-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('headline',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='head_line',
            new_name='headline',
        ),
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appo.Reporter'),
        ),
    ]
