# Generated by Django 2.2.2 on 2019-07-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0002_auto_20190609_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='last_name',
        ),
    ]
