# Generated by Django 2.2.2 on 2019-07-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0003_auto_20190705_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
